// ═══════════════════════════════════════════════
//  BIRD DATA
//
//  HOW TO ADD A NEW BIRD — minimum required fields:
//  {
//    id:     'unique_snake_case',          // e.g. 'snowy_owl'
//    name:   'Display Name',              // e.g. 'Snowy Owl'
//    giving: "it's giving ...",           // GenZ one-liner
//    desc:   "Sprint description.",       // 2–3 sentences, personality
//    tags:   ['tag1','tag2','tag3'],      // used for quiz matching (see tag list below)
//    // wikiTitle: 'Wikipedia Article'   // OPTIONAL — only if name ≠ Wikipedia page title
//  }
//
//  AVAILABLE TAGS (use any combo):
//  energy:  chaotic | focused | chill | intense | mysterious
//  mood:    energetic | determined | elegant | weird | fast | loud | patient | nocturnal
//  type:    feature | bugfix | debt | discovery | infra
//  flavour: colorful | powerful | precise | hidden | beautiful | scrappy | rare | dino
// ═══════════════════════════════════════════════
const BIRDS = [
  {
    id: 'cassowary',
    name: 'Cassowary',
    giving: "it's giving ancient, unhinged danger",
    desc: "You're not here to make friends. This sprint is primal, powerful, and slightly terrifying. The Cassowary doesn't know the word 'blocker' — it IS the blocker. Third tallest bird on Earth. Has a casque on its head for unclear reasons. Respect the process. Fear the deadline.",
    tags: ['chaotic','intense','powerful','feature','weird','dino'],
  },
  {
    id: 'shoebill',
    name: 'Shoebill',
    giving: "it's giving unblinking senior engineer",
    desc: "The Shoebill has seen things. It will stand completely still for six hours before striking with perfect precision. This sprint is quiet, deliberate, and when it moves, it MOVES. Everyone else is scared of it and that's correct.",
    tags: ['focused','mysterious','intense','patient','dino','discovery'],
  },
  {
    id: 'secretary_bird',
    name: 'Secretary Bird',
    giving: "it's giving corporate assassin in heels",
    desc: "Walks the savanna stomping snakes to death with power legs. Somehow wears its feathers like a pinstriped suit with a crest like a quill pen behind the ear. This sprint has executive function AND executive presence. Your blockers will be kicked.",
    tags: ['focused','intense','powerful','feature','determined','dino'],
  },
  {
    id: 'emu',
    name: 'Emu',
    giving: "it's giving lost the war (and fully thriving)",
    desc: "Historically defeated in The Great Emu War of 1932 when Australia sent soldiers against them. The emus won. The Emu sprint knows obstacles are coming and simply... keeps walking forward. You cannot stop the Emu. Australia tried.",
    tags: ['chaotic','determined','weird','infra','dino','chill'],
  },
  {
    id: 'ostrich',
    name: 'Ostrich',
    giving: "it's giving head down, full execution mode",
    desc: "Fastest land bird alive — 45mph. Does NOT bury its head in the sand, that's a myth propagated by people who fear commitment. The Ostrich sprint is about pure execution at full speed. Scope is locked. Communication is minimal. Let's GO.",
    tags: ['fast','focused','determined','infra','powerful','dino'],
  },
  {
    id: 'southern_ground_hornbill',
    name: 'Southern Ground Hornbill',
    giving: "it's giving old money danger, no rush",
    desc: "Slow. Deliberate. Lives 60+ years. Has a call that carries 10km. The Southern Ground Hornbill sprint is methodical and deeply consequential. It will not be rushed. Every ticket in this sprint was worth doing and everyone secretly knew it.",
    tags: ['determined','patient','debt','powerful','mysterious','dino'],
  },
  {
    id: 'potoo',
    name: 'Great Potoo',
    giving: "it's giving existential screaming (but make it chic)",
    desc: "Looks like it just received news it wasn't ready for. The Great Potoo is a master of disguise that somehow always ends up visible anyway. This sprint is giving 'trying to appear normal but we all know'. Nocturnal. Chaotic. Iconic.",
    tags: ['weird','chaotic','nocturnal','mysterious','unhinged','bugfix'],
  },
  {
    id: 'kakapo',
    name: 'Kakapo',
    giving: "it's giving critically endangered chaos goblin",
    desc: "World's only flightless parrot. Nocturnal. Nearly extinct. Extremely rare. Has a boom system where it inflates itself and calls from a bowl it dug. This sprint is so singular that future generations will tell stories about it.",
    tags: ['weird','chaotic','nocturnal','discovery','unhinged','rare'],
  },
  {
    id: 'peregrine_falcon',
    name: 'Peregrine Falcon',
    giving: "it's giving terminal velocity productivity",
    desc: "Fastest animal on the planet at 240mph in a dive. No meetings that could be emails. No unnecessary review cycles mid-stoop. The Peregrine sprint is clean, precise, and over before anyone realized what was happening.",
    tags: ['focused','fast','precise','feature','bugfix','intense'],
  },
  {
    id: 'harpy_eagle',
    name: 'Harpy Eagle',
    giving: "it's giving apex predator, main character",
    desc: "Largest, most powerful eagle on Earth. Talons the size of grizzly bear claws. The Harpy Eagle sprint has enormous scope, maximum impact, and a wingspan that casts a shadow over everything else on the roadmap.",
    tags: ['powerful','intense','feature','chaotic','loud','dino'],
  },
  {
    id: 'flamingo',
    name: 'Flamingo',
    giving: "it's giving resort era, everything is fine",
    desc: "Standing on one leg because frankly two legs is too much commitment. Pink from the inside out due to diet. The Flamingo sprint looks effortless from the outside, but the algorithm running underneath is surprisingly complex. It's giving coping.",
    tags: ['chill','elegant','colorful','discovery','calm','beautiful'],
  },
  {
    id: 'peacock',
    wikiTitle: 'Indian peafowl',
    name: 'Peacock',
    giving: "it's giving main character energy, no notes",
    desc: "Why ship a feature quietly when you can ship it with 200 iridescent feathers fanned out behind you? The Peacock sprint understands that presentation is half the delivery. Demo day will be an event. Invite stakeholders.",
    tags: ['loud','colorful','energetic','feature','bold','chaotic','hyped'],
  },
  {
    id: 'toucan',
    name: 'Keel-billed Toucan',
    giving: "it's giving tropical maximalist, served fresh",
    desc: "Has a beak that is one-third of its body length just because it could. This sprint said more is more and we are HERE for it. Big scope, big colors, big features, and absolutely no feedback on the color scheme because it's perfect.",
    tags: ['colorful','loud','chaotic','feature','energetic','hyped'],
  },
  {
    id: 'hummingbird',
    name: 'Ruby-throated Hummingbird',
    giving: "it's giving speed run, 100% completion",
    desc: "Heart beats 1,200 times per minute. Wings beat 80 times per second. The Hummingbird sprint moves so fast that slow-motion replays are required to understand what actually shipped. Unmatched velocity. Tiny but mighty.",
    tags: ['fast','focused','intense','feature','energetic','precise'],
  },
  {
    id: 'crow',
    name: 'Crow',
    giving: "it's giving dark academia mastermind",
    desc: "Crows remember individual human faces. They hold grudges for years. They also leave gifts for people they like. This sprint is intelligent, slightly gothic, and WILL find the optimal solution while quietly judging everyone else's approach.",
    tags: ['focused','mysterious','smart','discovery','nocturnal','determined'],
  },
  {
    id: 'raven',
    name: 'Common Raven',
    giving: "it's giving gothic genius, understands the assignment",
    desc: "Top 5 most intelligent animals on Earth. Can plan for the future, solve puzzles, and understand cause and effect. The Raven sprint has done the prep work. It knows what's coming. It's three steps ahead. Trust the process.",
    tags: ['mysterious','focused','discovery','nocturnal','powerful','smart'],
  },
  {
    id: 'owl_great_horned',
    wikiTitle: 'Great horned owl',
    name: 'Great Horned Owl',
    giving: "it's giving 3am enlightenment",
    desc: "Apex predator of the night sky. Knows things you don't know. Has been watching since before you were in the building. The Great Horned Owl sprint holds the accumulated wisdom of every previous sprint and deploys it ruthlessly at 3am.",
    tags: ['nocturnal','mysterious','focused','powerful','discovery','wise'],
  },
  {
    id: 'snowy_owl',
    name: 'Snowy Owl',
    giving: "it's giving ethereal, untouchable, iconic",
    desc: "Pure white, completely silent in flight, visible for kilometers. The Snowy Owl sprint looks impossible from the outside and then simply delivers, without ceremony, without explanation. The team is left wondering how it happened.",
    tags: ['calm','elegant','mysterious','focused','nocturnal','infra'],
  },
  {
    id: 'barn_owl',
    name: 'Barn Owl',
    giving: "it's giving silent but absolutely lethal",
    desc: "Hunts in complete darkness using hearing alone. Zero margin for error, zero noise. The Barn Owl sprint operates on intuition and extremely good pattern recognition. Nobody sees it coming. It ships at 3am without a Slack message.",
    tags: ['nocturnal','mysterious','focused','infra','hidden','precise'],
  },
  {
    id: 'penguin',
    name: 'Emperor Penguin',
    giving: "it's giving waddling through it together",
    desc: "Survives -60°C Antarctic winters by standing in a communal huddle, rotating so everyone gets warm. Nobody makes it through alone. The Penguin sprint is the definition of team sport — rotate, support, and you all cross the finish line.",
    tags: ['determined','team','patient','debt','chill','persistent'],
  },
  {
    id: 'puffin',
    name: 'Atlantic Puffin',
    giving: "it's giving tiny menace, enormous delivery",
    desc: "Looks like a penguin dressed for a gala. Can carry 62 fish in its beak simultaneously. The Puffin sprint punches dramatically above its weight class and looks incredibly stylish doing it. Underestimated every time. Never should be.",
    tags: ['determined','fast','persistent','bugfix','colorful','scrappy'],
  },
  {
    id: 'blue_footed_booby',
    name: 'Blue-footed Booby',
    giving: "it's giving unexplainable confident energy",
    desc: "The entire mating ritual is just presenting your blue feet and hoping for the best. This sprint has that same confident, slightly unhinged energy. We don't fully understand why the approach works. It works. Ship it.",
    tags: ['weird','chaotic','colorful','feature','unhinged','discovery'],
  },
  {
    id: 'kookaburra',
    wikiTitle: 'Laughing kookaburra',
    name: 'Kookaburra',
    giving: "it's giving laughing through the chaos",
    desc: "Makes a sound identical to maniacal laughter at sunrise. This sprint team knows that if you don't laugh at the bugs in production, you'll cry. The Kookaburra team finishes the sprint, looks at each other across the Zoom, and laughs.",
    tags: ['chaotic','energetic','loud','unhinged','bugfix','team'],
  },
  {
    id: 'lyrebird',
    name: 'Superb Lyrebird',
    giving: "it's giving absorbs everything, outputs everything",
    desc: "Can perfectly mimic chainsaws, camera shutters, car alarms, and other birds. The Lyrebird sprint is a synthesis sprint — gather all inputs, process everything, then produce something that contains multitudes. May sound like a construction site.",
    tags: ['chaotic','energetic','weird','discovery','loud','curious'],
  },
  {
    id: 'quetzal',
    name: 'Resplendent Quetzal',
    giving: "it's giving mythical rare glow-up",
    desc: "Considered sacred by the ancient Maya. Tail feathers up to a meter long. The Quetzal sprint is a rare gem — people will reference this one for years. A sprint that simply could not exist anywhere else. You are witnessing history.",
    tags: ['colorful','mysterious','beautiful','discovery','rare','ethereal'],
  },
  {
    id: 'hoopoe',
    name: 'Eurasian Hoopoe',
    giving: "it's giving desert royalty, unexpected drip",
    desc: "Has a crown. Is literally called a Hoopoe. Sacred in ancient Egypt. Was voted Europe's favourite bird. The Hoopoe sprint arrives from seemingly nowhere with incredible energy, solves the thing everyone else ignored, and ascends.",
    tags: ['colorful','mysterious','weird','discovery','exotic','curious'],
  },
  {
    id: 'mandarin_duck',
    name: 'Mandarin Duck',
    giving: "it's giving drip check: fully passed",
    desc: "Widely considered the most beautiful duck in the world. Arrived exactly like this. The Mandarin Duck sprint understands that aesthetics are non-negotiable — the UI will be beautiful, the code will be clean, and the demo will be iconic.",
    tags: ['colorful','elegant','beautiful','chill','feature','stylish'],
  },
  {
    id: 'kingfisher',
    name: 'Common Kingfisher',
    giving: "it's giving precision strike, get in get out",
    desc: "Dives at 40km/h, hits the target every single time, is back on the branch before anyone noticed. The Kingfisher sprint is clean execution — targeted, fast, and startlingly beautiful in its efficiency. Zero wasted motion.",
    tags: ['fast','precise','focused','bugfix','colorful','intense'],
  },
  {
    id: 'albatross',
    name: 'Wandering Albatross',
    giving: "it's giving long haul, no shortcuts allowed",
    desc: "Wingspan of 3.5 meters — largest of any living bird. Can fly for literal years without landing. The Albatross sprint is a marathon disguised as a sprint. Glide efficiently, conserve energy, and trust the very long process.",
    tags: ['determined','patient','debt','infra','persistent','calm'],
  },
  {
    id: 'pelican',
    name: 'Brown Pelican',
    giving: "it's giving big mouth, even bigger backlog",
    desc: "Holds 3 gallons of water in its expandable pouch. Dives headfirst from 20 meters. The Pelican sprint loaded up an enormous backlog and is now executing a controlled crash dive directly into it. The planning was done. We're in it now.",
    tags: ['chaotic','powerful','intense','feature','loud','energetic'],
  },
  {
    id: 'roadrunner',
    name: 'Greater Roadrunner',
    giving: "it's giving chaos with direction",
    desc: "Actually reaches 20mph. Is absolutely a real bird. Routinely eats rattlesnakes. The Roadrunner sprint is fast, slightly unhinged, leaves a cartoon dust cloud where it was, and somehow gets there first. Never underestimate.",
    tags: ['fast','chaotic','determined','bugfix','energetic','weird'],
  },
  {
    id: 'frigatebird',
    name: 'Magnificent Frigatebird',
    giving: "it's giving sky pirate, zero regrets",
    desc: "Steals food from other birds mid-flight as a primary strategy. Can't even land on water despite being a seabird. Lives entirely on its own terms. The Frigatebird sprint is not above borrowing a clever approach. The end result is magnificent.",
    tags: ['chaotic','intense','powerful','feature','determined','loud'],
  },
  {
    id: 'scarlet_macaw',
    name: 'Scarlet Macaw',
    giving: "it's giving loud colors, louder opinions",
    desc: "Screams. Always. Possibly in multiple languages. The Scarlet Macaw sprint has a lot of strong opinions in standup, a Slack thread that moves at light speed, and ships anyway because the energy is genuinely contagious.",
    tags: ['loud','colorful','chaotic','feature','energetic','unhinged','hyped'],
  },
  {
    id: 'bald_eagle',
    name: 'Bald Eagle',
    giving: "it's giving national importance, high altitude",
    desc: "Screams from above. Sees everything from 2km away. Delivers. The Bald Eagle sprint has been on the roadmap since Q1 and it is finally, finally happening. This is the sprint that makes the whole product architecture make sense.",
    tags: ['powerful','focused','intense','feature','determined','loud'],
  },
  {
    id: 'woodpecker',
    name: 'Pileated Woodpecker',
    giving: "it's giving relentless, skull full of ambition",
    desc: "Drums at 20 hits per second and has zero headaches due to specialized skull anatomy. Architecturally dismantles entire trees. The Woodpecker sprint is persistent and structural. It will make a very loud noise until the problem is fully solved.",
    tags: ['persistent','focused','intense','infra','debt','determined'],
  },
  {
    id: 'swift',
    name: 'Common Swift',
    giving: "it's giving airborne for months, no landing required",
    desc: "Can stay in flight for 10 consecutive months. Eats, sleeps, and mates in the air. The Swift sprint has zero downtime and is not touching ground until the feature is deployed. An engineering marvel. There will be no retro until it's done.",
    tags: ['fast','focused','intense','infra','determined','nocturnal'],
  },
  {
    id: 'bird_of_paradise',
    wikiTitle: 'Greater bird-of-paradise',
    name: 'Bird of Paradise',
    giving: "it's giving nature said absolutely no limits",
    desc: "Evolved in isolation until the feature set got completely out of hand — in the best way possible. The Bird of Paradise sprint let design take the wheel and there are zero regrets. The competition's product will look extremely beige.",
    tags: ['chaotic','colorful','weird','feature','beautiful','unhinged'],
  },
  {
    id: 'victoria_crowned_pigeon',
    wikiTitle: 'Victoria crowned pigeon',
    name: 'Victoria Crowned Pigeon',
    giving: "it's giving royalty that snuck in as a pigeon",
    desc: "World's largest pigeon. Has an elaborate blue lace crown. Nobody expected the pigeon to show up like this. The Victoria Crowned Pigeon sprint is the surprise drop — looks ordinary on the ticket, turns out to be deeply extraordinary.",
    tags: ['elegant','colorful','weird','beautiful','discovery','calm'],
  },
  {
    id: 'bee_eater',
    name: 'European Bee-eater',
    giving: "it's giving precision, pure color, absolute slay",
    desc: "Catches bees in mid-flight, rubs out the stinger methodically before eating, then does it again. Has completely solved the bee problem. The Bee-eater sprint handles dangerous components with elegance and ships the most beautiful result.",
    tags: ['precise','colorful','focused','fast','feature','elegant'],
  },
  {
    id: 'sandhill_crane',
    name: 'Sandhill Crane',
    giving: "it's giving elegant migration, team sport",
    desc: "Migrates in enormous flocks. Mates for life. Has a prehistoric rattling call that carries for miles. The Sandhill Crane sprint is a team movement — everyone migrating in the same direction, in formation, toward something meaningful.",
    tags: ['determined','team','elegant','feature','patient','beautiful'],
  },
  {
    id: 'spoonbill',
    name: 'Roseate Spoonbill',
    giving: "it's giving pink energy, chaotic toolkit, results",
    desc: "Has a spoon for a face and swings it through water at random until food appears. Somehow this works every time. The Spoonbill sprint has an unconventional methodology that looks chaotic from the outside and consistently delivers pink-tinted magic.",
    tags: ['chaotic','colorful','weird','discovery','chill','team'],
  },
  {
    id: 'macaroni_penguin',
    name: 'Macaroni Penguin',
    giving: "it's giving pasta head unhinged icon",
    desc: "Has bright yellow-orange eyebrow plumes that look exactly like pasta. Named after 18th century fashion. The Macaroni Penguin sprint is iconic for reasons that genuinely cannot be explained. The team has matching energy. 'And called it macaroni.'",
    tags: ['chaotic','weird','colorful','unhinged','team','bugfix'],
  },
  {
    id: 'nuthatch',
    name: 'White-breasted Nuthatch',
    giving: "it's giving upside-down on everything, thriving",
    desc: "The only bird that routinely walks headfirst down tree trunks as its primary method of movement. Simply chose a different perspective. The Nuthatch sprint approaches the problem from the angle nobody else tried and finds something everyone missed.",
    tags: ['weird','curious','discovery','focused','persistent','calm'],
  },
  {
    id: 'frogmouth',
    name: 'Tawny Frogmouth',
    giving: "it's giving branch cosplay as a coping mechanism",
    desc: "Disguises itself as a broken branch so convincingly the images look photoshopped. The Frogmouth sprint is deep in stealth mode — under the radar, blending in, quietly accumulating wins. The demo reveal will be genuinely shocking.",
    tags: ['hidden','nocturnal','mysterious','infra','chill','weird'],
  },
  {
    id: 'robin',
    name: 'American Robin',
    giving: "it's giving fresh start, spring has arrived",
    desc: "First bird of spring, every spring, reliably. Shows up exactly when needed. The Robin sprint is a new beginning — first sprint on a new project, or a reset after a brutal quarter. The red chest is hope. Things are genuinely looking up.",
    tags: ['hopeful','energetic','feature','determined','calm','fresh'],
  },
  {
    id: 'bearded_vulture',
    name: 'Bearded Vulture',
    giving: "it's giving drop the bone from height and extract value",
    desc: "Drops bones from great heights onto rocks to crack them and eat the marrow — the part nobody else wanted. Also stains its feathers orange with iron-rich soil for style reasons. Extracts value from where others saw nothing. Underrated icon.",
    tags: ['determined','cleanup','debt','intense','weird','focused'],
  },
  {
    id: 'blue_jay',
    name: 'Blue Jay',
    giving: "it's giving bold, loud, and actually right",
    desc: "Extremely loud. Will argue with a hawk. Has strong opinions about everything. Is usually correct. The Blue Jay sprint knows its architecture decisions are correct and is not afraid to defend them at volume. PR comments will be substantial.",
    tags: ['loud','colorful','energetic','focused','feature','bold'],
  },
  {
    id: 'cardinal',
    name: 'Northern Cardinal',
    giving: "it's giving one pop of color that changes everything",
    desc: "One cardinal in a grey winter scene and suddenly it's a painting. The Cardinal sprint is that feature — the one that sounds small in the ticket but makes the whole product click. Visual impact. Emotional resonance. Zero unnecessary scope.",
    tags: ['colorful','focused','feature','elegant','bold','determined'],
  },
  {
    id: 'nighthawk',
    name: 'Common Nighthawk',
    giving: "it's giving nocturnal grind season",
    desc: "Active at dusk. Invisible during the day. The Nighthawk sprint operates in the hours when Slack is quiet and git commits speak louder than standups. Something significant is being built in the dark. The morning reveals it fully formed.",
    tags: ['nocturnal','mysterious','hidden','infra','focused','intense'],
  },
  {
    id: 'swift_parrot',
    name: 'Swift Parrot',
    giving: "it's giving fast, endangered, not slowing down",
    desc: "Fastest parrot alive. Critically endangered. Shows up every year anyway and gets the job done. The Swift Parrot sprint is racing against the clock with full awareness and full commitment. Nothing about this sprint is casual. Everything matters.",
    tags: ['fast','intense','colorful','determined','feature','focused'],
  },
  {
    id: 'wren',
    name: 'Pacific Wren',
    giving: "it's giving smallest and most opinionated",
    desc: "Among the smallest birds on Earth. Has one of the loudest songs relative to body size. The Wren sprint underestimated nothing, argued about everything in planning, and shipped the cleanest code in the codebase. Size is completely irrelevant.",
    tags: ['small','intense','determined','bugfix','persistent','loud'],
  },
  {
    id: 'spoonbill_eurasian',
    name: 'Eurasian Spoonbill',
    giving: "it's giving elegant chaos, yes both",
    desc: "Completely white. Has a spoon. Sweeps gracefully through water. The Eurasian Spoonbill sprint is elegant in execution and chaotic in planning, and somehow the elegance wins. People will say it looked effortless. It was not effortless.",
    tags: ['elegant','chaotic','chill','discovery','beautiful','team'],
  },
  {
    id: 'shoebill_alt',
    wikiTitle: 'Shoebill',
    name: 'Whale-headed Stork',
    giving: "it's giving motionless... then suddenly EVERYTHING",
    desc: "Alternate name for the Shoebill — because one name wasn't enough for this energy. Stands motionless in swamp for hours. Blinks once. Then strikes with the force of a revelation. This sprint had one week of planning silence and then shipped six features.",
    tags: ['focused','patient','intense','powerful','mysterious','dino'],
  },
  {
    id: 'hornbill',
    name: 'Great Hornbill',
    giving: "it's giving casque on the head, unbothered",
    desc: "Has a massive yellow casque on top of its beak for no structural reason — scientists think it's purely for display. The Great Hornbill sprint carries some extra weight that looks unnecessary but makes the whole thing more impressive somehow.",
    tags: ['colorful','weird','bold','feature','loud','powerful'],
  },
  {
    id: 'sunbird',
    name: 'Malachite Sunbird',
    giving: "it's giving iridescent green excellence",
    desc: "Metallic emerald green from beak to tail. Africa's answer to the hummingbird. The Malachite Sunbird sprint moves fast, looks incredible, and pollinates everything it touches. Every ticket it closes makes the next sprint better.",
    tags: ['fast','colorful','elegant','feature','energetic','beautiful'],
  },
  {
    id: 'ibis',
    name: 'Scarlet Ibis',
    giving: "it's giving scarlet, no apologies",
    desc: "The most vivid red of any bird. Gets its color from the same place flamingos get pink: from eating things. The Scarlet Ibis sprint commits completely to its color — no hedging, no off-ramps, pure commitment to the chosen direction.",
    tags: ['colorful','determined','bold','feature','loud','beautiful'],
  },
  {
    id: 'anhinga',
    name: 'Anhinga',
    giving: "it's giving spread out to dry, recovering",
    desc: "Dives deep, gets completely soaked because its feathers aren't waterproof by design, then stands with wings spread to dry in the sun. The Anhinga sprint came out the other side a bit waterlogged but is spreading out in the retrospective sun.",
    tags: ['chill','weird','patient','debt','determined','calm'],
  },

  // ── 100 new birds ──────────────────────────────
  {
    id: 'bar_tailed_godwit',
    wikiTitle: 'Bar-tailed godwit',
    name: 'Bar-tailed Godwit',
    giving: "it's giving 11,000km non-stop, zero excuses",
    desc: "Holds the world record for longest non-stop migration — 11,000km from Alaska to New Zealand without eating, drinking, or sleeping. Its organs literally shrink mid-flight to fuel the journey. The Bar-tailed Godwit sprint has one mode: airborne until landed. No standups mid-flight.",
    tags: ['determined','intense','fast','feature','infra','persistent'],
  },
  {
    id: 'arctic_tern',
    name: 'Arctic Tern',
    giving: "it's giving sees more sunlight than any creature alive",
    desc: "Migrates pole to pole every year — up to 70,000km round trip. Sees two summers annually and more daylight than any other animal on Earth. The Arctic Tern sprint spans the full scope of the product and somehow still finishes ahead of schedule.",
    tags: ['determined','fast','intense','feature','energetic','persistent'],
  },
  {
    id: 'kea',
    name: 'Kea',
    giving: "it's giving alpine genius who also destroyed your car",
    desc: "World's only alpine parrot. Intelligent enough to solve multi-step puzzle boxes. Also systematically dismantles car windshield wipers for entertainment. The Kea sprint approaches every problem from an angle nobody predicted, solves it brilliantly, and removes one thing that seemed load-bearing.",
    tags: ['chaotic','curious','smart','discovery','weird','determined'],
  },
  {
    id: 'northern_gannet',
    name: 'Northern Gannet',
    giving: "it's giving 100mph commitment, no mid-stoop pivots",
    desc: "Spots fish from 40 meters, folds wings, and hits water at 100mph. Eyes are positioned forward for perfect binocular dive precision. Air sacs under the skin cushion the impact. The Gannet sprint commits completely to the chosen architecture. Trust the angle.",
    tags: ['fast','focused','precise','intense','feature','determined'],
  },
  {
    id: 'painted_bunting',
    name: 'Painted Bunting',
    giving: "it's giving paint.exe ran with no budget limits",
    desc: "The most colorful bird in North America: blue head, red underparts, green back. Each color region was apparently designed independently with no design review. The Painted Bunting sprint had a design system and chose to use every token simultaneously. Correct.",
    tags: ['colorful','beautiful','feature','bold','energetic','elegant'],
  },
  {
    id: 'green_heron',
    name: 'Green Heron',
    giving: "it's giving built a tool to catch the fish first",
    desc: "One of the rare birds that uses bait — places insects or leaves on the water surface to lure fish to striking distance. Uses tools. The Green Heron sprint built an internal utility before solving the actual problem. Two deliverables shipped. Efficiency.",
    tags: ['smart','focused','discovery','patient','curious','infra'],
  },
  {
    id: 'whooping_crane',
    name: 'Whooping Crane',
    giving: "it's giving 15 individuals to 800, comeback unlocked",
    desc: "Down to 15 birds in 1941. Now over 800, recovered through decades of intensive intervention. Tallest bird in North America. The Whooping Crane sprint inherited a codebase at critical failure and shipped a full system turnaround. Against all prior assessments.",
    tags: ['determined','persistent','hopeful','feature','powerful','rare'],
  },
  {
    id: 'sunbittern',
    name: 'Sunbittern',
    giving: "it's giving hidden reveal that stopped everyone cold",
    desc: "Looks like a plain brown wading bird. Spreads wings to reveal giant eye-spots mimicking an owl face. The Sunbittern sprint was listed as a maintenance ticket. Demo day revealed it contained six undisclosed features. Scope was always there.",
    tags: ['mysterious','hidden','weird','feature','discovery','patient'],
  },
  {
    id: 'cock_of_the_rock',
    wikiTitle: 'Andean cock-of-the-rock',
    name: 'Cock of the Rock',
    giving: "it's giving lek energy, stakeholders are watching",
    desc: "Males gather at competitive display grounds and perform simultaneously to be selected by females. Neon orange crest, slate wings. The Cock of the Rock sprint is a demo-day sprint — every ticket is a performance. All eyes are on the stage.",
    tags: ['colorful','loud','chaotic','feature','energetic','bold'],
  },
  {
    id: 'three_wattled_bellbird',
    wikiTitle: 'Three-wattled bellbird',
    name: 'Three-wattled Bellbird',
    giving: "it's giving loudest bird in the Americas, warranted",
    desc: "Loudest bird in the Western Hemisphere at over 100 decibels close range. Has three fleshy wattles dangling from the beak like abstract art. The Bellbird sprint announces itself. The launch email thread will be long. The Slack announcement will ping everyone.",
    tags: ['loud','intense','chaotic','feature','energetic','bold'],
  },
  {
    id: 'purple_gallinule',
    name: 'Purple Gallinule',
    giving: "it's giving iridescent, walks on water, fully unbothered",
    desc: "Walks across floating lily pads using enormous toes that distribute weight across the surface. Iridescent blue-purple body with a candy-corn beak. The Purple Gallinule sprint operates on infrastructure that shouldn't support the load. It distributes perfectly.",
    tags: ['colorful','elegant','weird','discovery','focused','beautiful'],
  },
  {
    id: 'harris_hawk',
    wikiTitle: "Harris's hawk",
    name: "Harris's Hawk",
    giving: "it's giving cooperative hunt, distinct roles, one result",
    desc: "The only raptor that hunts in organized cooperative packs — one flushes, one blocks, one strikes. No redundant effort. The Harris's Hawk sprint had distinct responsibilities, zero overlap, and the prey had nowhere to go. Perfect squad execution.",
    tags: ['focused','team','fast','intense','bugfix','determined'],
  },
  {
    id: 'long_tailed_widowbird',
    name: 'Long-tailed Widowbird',
    giving: "it's giving tail 3x body length, worth every pixel",
    desc: "Males grow tails three times their body length during mating season. Flight is measurably impaired. They grow them anyway because the display is that important. The Long-tailed Widowbird sprint carried significant overhead and shipped the most memorable demo of the quarter.",
    tags: ['bold','colorful','chaotic','feature','weird','intense'],
  },
  {
    id: 'reddish_egret',
    name: 'Reddish Egret',
    giving: "it's giving chaotic fishing dance, catches more than anyone",
    desc: "Hunts by sprinting, spinning, spreading wings like an umbrella, and generally moving like something has gone wrong. Catches more fish than its composed relatives. The Reddish Egret sprint has an unusual process that concerned everyone in planning and exceeded every metric in review.",
    tags: ['chaotic','energetic','weird','bugfix','determined','fast'],
  },
  {
    id: 'rockhopper_penguin',
    name: 'Rockhopper Penguin',
    giving: "it's giving jumps everywhere instead of walking, iconic",
    desc: "Rather than waddling like sensible penguins, the Rockhopper hops — up cliff faces, over boulders, between rocks. Has spiky yellow eyebrows that communicate constant mild outrage. The Rockhopper sprint chose the harder path, arrived at the same destination, and looked better doing it.",
    tags: ['determined','energetic','weird','infra','persistent','fast'],
  },
  {
    id: 'gentoo_penguin',
    name: 'Gentoo Penguin',
    giving: "it's giving fastest swimmer in the bird division",
    desc: "Fastest swimming bird alive at 22mph. Builds pebble nests and is documented stealing pebbles from neighbors. The Gentoo sprint is pure underwater velocity — no flights, no detours, just efficient execution and some dependency borrowing that everyone quietly noticed.",
    tags: ['fast','focused','energetic','feature','determined','precise'],
  },
  {
    id: 'black_swan',
    name: 'Black Swan',
    giving: "it's giving nobody expected this, changes everything",
    desc: "Europeans assumed for centuries all swans were white — until the Dutch reached Australia in 1697. The Black Swan became the philosophical metaphor for high-impact unforeseen events. This sprint was not on the roadmap. It redefines the product.",
    tags: ['mysterious','weird','powerful','discovery','rare','chaotic'],
  },
  {
    id: 'hawfinch',
    name: 'Hawfinch',
    giving: "it's giving 50kg of bite force, quiet about it",
    desc: "Can apply 50 kilograms of crushing force through its beak to crack olive and cherry stones. One of Europe's most secretive birds — widespread but rarely observed. The Hawfinch sprint solved the hardest problem in the backlog without announcing it.",
    tags: ['powerful','focused','hidden','patient','mysterious','infra'],
  },
  {
    id: 'wood_duck',
    name: 'Wood Duck',
    giving: "it's giving most beautiful duck, also jumps from trees",
    desc: "Nests in tree cavities up to 15 meters high. On their first day of life, ducklings leap out and bounce. Considered among the most beautiful ducks on Earth. The Wood Duck sprint shipped extraordinary features on day one from a completely unconventional starting point.",
    tags: ['colorful','beautiful','fast','feature','bold','energetic'],
  },
  {
    id: 'burrowing_owl',
    name: 'Burrowing Owl',
    giving: "it's giving underground ops, rattlesnake voice activated",
    desc: "Lives in underground burrows, often repurposed from prairie dogs. When threatened, can mimic a rattlesnake from inside the burrow. Tiny, fierce, territorial. The Burrowing Owl sprint runs from a non-standard environment and defends its position with alarming effectiveness.",
    tags: ['hidden','nocturnal','weird','infra','determined','mysterious'],
  },
  {
    id: 'snowy_egret',
    name: 'Snowy Egret',
    giving: "it's giving white gloves, golden slippers, don't test it",
    desc: "Pure white plumage, bright golden feet it shuffles through water to disturb fish. Hunted to near-extinction in the 1800s for its feathers alone. The Snowy Egret sprint looks impossibly elegant. No stakeholder sees what's coming until the fish is already gone.",
    tags: ['elegant','beautiful','focused','precise','determined','feature'],
  },
  {
    id: 'gouldian_finch',
    name: "Gouldian Finch",
    giving: "it's giving color system complete, no further input required",
    desc: "Three distinct head color morphs — red, yellow, or black — in the same species. Body is always turquoise, purple, and green regardless. Exists in Australia. The Gouldian Finch sprint didn't need a design system. It arrived as the design system.",
    tags: ['colorful','beautiful','feature','bold','elegant','weird'],
  },
  {
    id: 'kiwi',
    wikiTitle: 'Brown kiwi',
    name: 'Brown Kiwi',
    giving: "it's giving night shift, smells out the answer",
    desc: "Only bird with nostrils at the tip of its beak — finds food entirely by smell in total darkness. Lays an egg 20% of its body weight, equivalent proportionally to a human giving birth to a six-year-old. The Kiwi sprint is built differently. The output is enormous relative to visible effort.",
    tags: ['nocturnal','weird','determined','persistent','infra','focused'],
  },
  {
    id: 'takahe',
    name: 'Takahē',
    giving: "it's giving thought extinct for 50 years, still here",
    desc: "Declared extinct in 1898. Rediscovered alive in a remote New Zealand valley in 1948. Still endangered but persisting. The Takahē sprint is the legacy codebase sprint — everyone assumed it was dead, it just needed someone to go look in the right directory.",
    tags: ['determined','persistent','weird','debt','rare','hopeful'],
  },
  {
    id: 'weka',
    name: 'Weka',
    giving: "it's giving flightless, extremely curious, has your keys",
    desc: "Flightless New Zealand rail. Intensely curious — walks into tents and takes anything shiny. Researchers have had car keys stolen by Wekas. The Weka sprint investigated every corner of the codebase, took what it needed without asking, and delivered with zero explanation.",
    tags: ['chaotic','curious','weird','discovery','energetic','determined'],
  },
  {
    id: 'sword_billed_hummingbird',
    name: 'Sword-billed Hummingbird',
    giving: "it's giving only tool that fits the one flower",
    desc: "The only bird in the world with a beak longer than its body. Evolved to reach a single species of Andean flower that no other bird can access. Mutual dependency. The Sword-billed Hummingbird sprint built an integration so specialized it unlocks exactly one problem — which is now completely solved.",
    tags: ['precise','focused','weird','feature','discovery','determined'],
  },
  {
    id: 'red_billed_quelea',
    name: 'Red-billed Quelea',
    giving: "it's giving billion-strong murmuration, scales infinitely",
    desc: "The most numerous wild bird on Earth — flocks exceed one billion individuals. Murmurations so dense they block out the sun. The Red-billed Quelea sprint is the large-team sprint: extraordinary individual coordination, emergent behavior at scale, and an output that is genuinely awe-inspiring from any vantage point.",
    tags: ['chaotic','energetic','loud','team','feature','colorful'],
  },
  {
    id: 'snowy_sheathbill',
    name: 'Snowy Sheathbill',
    giving: "it's giving the only bird doing the job nobody else wanted",
    desc: "Antarctica's only land bird with no webbed feet. Subsists on penguin feces, afterbirth, and carrion. Fills the scavenger niche nobody else claimed. The Sheathbill sprint is pure tech debt — entirely thankless, structurally essential, and the ecosystem would collapse without it.",
    tags: ['debt','determined','weird','infra','persistent','patient'],
  },
  {
    id: 'jacana',
    name: 'Northern Jacana',
    giving: "it's giving walks on lily pads, males raise the kids",
    desc: "Females are larger, more aggressive, and hold territories. Males build nests, incubate eggs, and raise chicks — often tucking eggs under wing-flaps to carry them while walking on floating vegetation. The Jacana sprint reversed the expected roles and the results were significantly better.",
    tags: ['weird','colorful','chaotic','feature','team','curious'],
  },
  {
    id: 'golden_eagle',
    name: 'Golden Eagle',
    giving: "it's giving mountain king, fastest dive of the eagles",
    desc: "Can reach 200mph in a dive. Large enough to take full-grown deer and mountain goats. Has been used by Kazakh nomads for wolf hunting for millennia. The Golden Eagle sprint drops from altitude, locks onto the critical path, and delivers maximum impact before anything else notices.",
    tags: ['powerful','fast','intense','focused','feature','determined'],
  },
  {
    id: 'oystercatcher',
    name: 'Eurasian Oystercatcher',
    giving: "it's giving two techniques, learned from parents, passed down",
    desc: "Has a beak shaped for two distinct strategies: stabbing or hammering bivalves. Young oystercatchers must be taught which method by their parents — the skill is culturally transmitted across generations. The Oystercatcher sprint carries institutional knowledge. Onboarding is the feature.",
    tags: ['focused','precise','determined','infra','patient','team'],
  },
  {
    id: 'rifleman',
    wikiTitle: 'New Zealand rifleman',
    name: 'Rifleman',
    giving: "it's giving New Zealand's smallest bird, enormous output",
    desc: "New Zealand's smallest bird at 6cm. Males flash iridescent green so bright they look like flying emeralds. Females are a perfect brown camouflage. The Rifleman sprint is the smallest ticket that turned into the highest-value delivery of the quarter. Size is not the metric.",
    tags: ['fast','energetic','focused','feature','small','colorful'],
  },
  {
    id: 'kokako',
    name: 'Kōkako',
    giving: "it's giving glides more than it flies, mournful and majestic",
    desc: "Has weak wings and glides between trees rather than flying. Has a haunting, flute-like call considered one of the most beautiful bird songs in the world. The Kōkako sprint moves at its own pace, covers the same ground differently, and leaves a sound in the codebase that persists long after.",
    tags: ['elegant','mysterious','chill','debt','patient','beautiful'],
  },
  {
    id: 'laysan_albatross',
    name: 'Laysan Albatross',
    giving: "it's giving dances for years before committing",
    desc: "Young Laysan Albatrosses spend up to five years perfecting an elaborate synchronised dance before choosing a mate for life. The dance has specific moves and must be learned and matched. The Laysan Albatross sprint had an extremely long discovery phase. The architecture is perfect. No changes.",
    tags: ['patient','elegant','determined','discovery','team','calm'],
  },
  {
    id: 'african_fish_eagle',
    wikiTitle: 'African fish eagle',
    name: 'African Fish Eagle',
    giving: "it's giving call that IS the sound of an entire continent",
    desc: "Its cry is so distinctive it's been called the 'Voice of Africa' — instantly recognizable, carries for kilometers. Dives from a perch, snatches fish from the surface with talons, returns to eat. The African Fish Eagle sprint has a signature everyone recognizes. The result arrives without warning.",
    tags: ['powerful','focused','fast','feature','determined','iconic'],
  },
  {
    id: 'greater_sage_grouse',
    name: 'Greater Sage-Grouse',
    giving: "it's giving inflated chest, dramatic entrance, everyone stares",
    desc: "Males inflate yellow air sacs on their chest and make a loud gurgling pop in a choreographed display at communal leks every spring. Has been doing this in the same meadows for thousands of years. The Sage-Grouse sprint has a very dramatic kickoff. Everyone attends. The spectacle is real.",
    tags: ['loud','colorful','chaotic','weird','feature','energetic'],
  },
  {
    id: 'bobolink',
    name: 'Bobolink',
    giving: "it's giving 20,000km migration, solo, no GPS",
    desc: "Migrates over 20,000km round trip from North America to South America. Has magnetic crystals in its skull that navigate using Earth's magnetic field. The Bobolink sprint runs independently with internal orientation. No external dependencies. The destination is always correct.",
    tags: ['determined','fast','focused','infra','persistent','mysterious'],
  },
  {
    id: 'wandering_tattler',
    name: 'Wandering Tattler',
    giving: "it's giving found everywhere, recognized by nobody",
    desc: "Breeds in remote Alaskan mountain streams and winters across every Pacific island group. Ubiquitous across the Pacific and consistently overlooked. The Wandering Tattler sprint is the invisible infrastructure sprint — running everywhere, named by almost nobody, quietly essential.",
    tags: ['infra','hidden','chill','patient','determined','calm'],
  },
  {
    id: 'red_knot',
    name: 'Red Knot',
    giving: "it's giving doubles weight before the launch, sprints anyway",
    desc: "Before migrating, the Red Knot doubles its body weight in two weeks. Organs shrink to make room for fat stores. Flies 11,000km non-stop on this fuel. The Red Knot sprint front-loads all preparation obsessively, then executes a single continuous run to delivery with zero context switches.",
    tags: ['determined','intense','fast','persistent','feature','infra'],
  },
  {
    id: 'dunlin',
    name: 'Dunlin',
    giving: "it's giving murmuration synchrony at 400 birds per second",
    desc: "Forms murmurations of hundreds of thousands that move as a single fluid organism. Response time between birds is 15 milliseconds. The coordination is not led — it's emergent. The Dunlin sprint is the fully-async distributed team sprint. Nobody is in charge. Everything ships.",
    tags: ['team','chaotic','energetic','fast','infra','determined'],
  },
  {
    id: 'avocet',
    name: 'American Avocet',
    giving: "it's giving upswept bill, sweeps the whole surface",
    desc: "Has an elegant upward-curved beak that sweeps side-to-side through shallow water. Changes from grey winter plumage to bright rust-orange for breeding. The Avocet sprint covers the full surface area of the problem with an elegant, sweeping approach that catches everything in its path.",
    tags: ['elegant','focused','determined','discovery','colorful','beautiful'],
  },
  {
    id: 'little_blue_penguin',
    wikiTitle: 'Little blue penguin',
    name: 'Little Blue Penguin',
    giving: "it's giving world's smallest penguin, world's biggest confidence",
    desc: "Smallest penguin species at 33cm. Parades home from sea to its burrow every evening in a group for safety. The Fairy Penguin sprint is underestimated at every planning session and reliably outperforms. The evening parade home is a ceremony worth attending.",
    tags: ['small','determined','chill','team','persistent','focused'],
  },
  {
    id: 'african_penguin',
    name: 'African Penguin',
    giving: "it's giving only penguin in Africa, fully committed to the bit",
    desc: "The only penguin species in Africa, thriving on the Benguela Current. Makes a sound identical to a donkey's bray. Called the 'jackass penguin' by sailors. The African Penguin sprint operates in a non-standard environment and sounds chaotic in standups. Delivery is always serious.",
    tags: ['weird','loud','determined','persistent','team','bugfix'],
  },
  {
    id: 'black_browed_albatross',
    name: 'Black-browed Albatross',
    giving: "it's giving eyebrows locked in permanent disapproval",
    desc: "Bold black eyebrow stripe gives it a permanent expression of judgmental disappointment. Nests in massive colonies on Antarctic islands. The Black-browed Albatross sprint radiates quiet disapproval for every process violation but ships consistently, every year, into the wind.",
    tags: ['determined','patient','intense','infra','calm','persistent'],
  },
  {
    id: 'turquoise_cotinga',
    name: 'Turquoise Cotinga',
    giving: "it's giving iridescent blue that doesn't seem real",
    desc: "Males are a structural iridescent turquoise so intense they appear backlit. Females are brown. The contrast is complete. The Turquoise Cotinga sprint has one team member whose contribution makes the entire result look illuminated. The rest of the team knows who it is.",
    tags: ['colorful','beautiful','mysterious','feature','elegant','rare'],
  },
  {
    id: 'magnificent_riflebird',
    name: 'Magnificent Riflebird',
    giving: "it's giving velvet wings, performance as engineering",
    desc: "Male fans iridescent velvet-black wings into a perfect circle frame. Performs a synchronized dance with the female who mirrors his moves. The Riflebird sprint is built as a performance — every component was designed to be seen. The architecture is the feature.",
    tags: ['colorful','beautiful','feature','elegant','bold','loud'],
  },
  {
    id: 'clark_nutcracker',
    name: "Clark's Nutcracker",
    giving: "it's giving caches 30,000 seeds, remembers all of them",
    desc: "Stores up to 30,000 pine seeds across hundreds of cache sites and retrieves them months later with extraordinary accuracy using spatial memory. Reforests mountains as a side effect. The Clark's Nutcracker sprint built exhaustive documentation and the next team launched three features from it.",
    tags: ['focused','smart','patient','infra','determined','discovery'],
  },
  {
    id: 'american_dipper',
    name: 'American Dipper',
    giving: "it's giving walks underwater, dips constantly, unbothered",
    desc: "Only aquatic songbird in North America — literally walks along riverbeds underwater. Blinks a white eyelid and dips its whole body rhythmically for no fully understood reason. The Dipper sprint operates in an environment everyone said was unsuitable. It dips. It delivers.",
    tags: ['weird','determined','infra','focused','persistent','chill'],
  },
  {
    id: 'red_crossbill',
    name: 'Red Crossbill',
    giving: "it's giving evolved specifically for one lock, one key",
    desc: "Beak crosses at the tip — evolved to pry open pine cones with a twisting motion. Nomadic: follows cone crops across continents. The Red Crossbill sprint built one specialized tool for one deeply specific problem. It works better than anything else that exists for this exact task.",
    tags: ['focused','precise','weird','infra','determined','fast'],
  },
  {
    id: 'cedar_waxwing',
    name: 'Cedar Waxwing',
    giving: "it's giving passes berries to teammates, mutual care",
    desc: "Cedar Waxwings famously pass food down a row of perched birds until each one has eaten. Sleek crested design, waxy red wing tips. The Cedar Waxwing sprint distributes credit, knowledge, and recognition as evenly as it distributes food. Everyone gets fed before anyone is full.",
    tags: ['team','elegant','colorful','chill','feature','patient'],
  },
  {
    id: 'american_bittern',
    name: 'American Bittern',
    giving: "it's giving blends into reeds, you walked past it twice",
    desc: "Freezes with beak pointed skyward and sways like a reed in wind when threatened. The camouflage is nearly perfect. Has been standing in the same codebase corner for years. The American Bittern sprint is the feature hiding in plain sight in the existing architecture. Just look at the reeds.",
    tags: ['hidden','mysterious','patient','infra','chill','focused'],
  },
  {
    id: 'trumpeter_swan',
    name: 'Trumpeter Swan',
    giving: "it's giving heaviest NA bird, loudest voice in the room",
    desc: "Heaviest native bird in North America at 12kg. Its call — a deep, resonant trumpet — carries across entire lakes. Near-extinct in 1935, now recovered. The Trumpeter Swan sprint has the biggest footprint in the system, announces its presence clearly, and simply cannot be missed.",
    tags: ['loud','powerful','determined','feature','bold','hopeful'],
  },
  {
    id: 'white_ibis',
    name: 'White Ibis',
    giving: "it's giving urban adaptation complete, thriving anyway",
    desc: "Highly adaptable wading bird that moved into cities when wetlands disappeared, foraging in parks and parking lots. Entirely unbothered by the urban environment. The White Ibis sprint encountered deprecated dependencies and found workarounds for every single one without changing the interface.",
    tags: ['determined','weird','chill','debt','infra','persistent'],
  },
  {
    id: 'american_avocet',
    wikiTitle: 'American avocet',
    name: 'American Avocet — Breeding',
    giving: "it's giving grey to rust in one molt, full transformation arc",
    desc: "Switches from silver-grey to vivid rust-orange head and neck during breeding season. Same bird, completely different energy. The Avocet Breeding sprint is the product going into launch mode — the system was always this capable. The color just had to change.",
    tags: ['colorful','elegant','feature','transformation','bold','energetic'],
  },
  {
    id: 'california_condor',
    name: 'California Condor',
    giving: "it's giving 3m wingspan, back from the brink of deletion",
    desc: "Largest flying bird in North America — 3-meter wingspan, 12kg. Went extinct in the wild in 1987 (27 birds in captivity total). Now over 500. The California Condor sprint was a complete rebuild from captive snapshots. It flies. It is majestic. The old architecture is preserved in its bones.",
    tags: ['powerful','determined','rare','infra','debt','hopeful'],
  },
  {
    id: 'limpkin',
    name: 'Limpkin',
    giving: "it's giving one skill, absolute mastery, screaming about it",
    desc: "Eats almost exclusively apple snails. Has a beak curved specifically to extract them from shells. Screams at top volume during breeding season, earning names like 'crying bird' and 'wailing bird.' The Limpkin sprint has one job, performs it with complete mastery, and is loud about the progress.",
    tags: ['focused','loud','weird','bugfix','determined','precise'],
  },
  {
    id: 'cuckoo',
    wikiTitle: 'Common cuckoo',
    name: 'Common Cuckoo',
    giving: "it's giving lays egg in someone else's repo",
    desc: "The Common Cuckoo lays its eggs in other birds' nests and leaves them to raise its young. The chick hatches early and ejects all other eggs. The Cuckoo sprint identified an existing service, contributed exactly one well-placed feature, and let the host team do the integration work.",
    tags: ['chaotic','mysterious','hidden','feature','smart','weird'],
  },
  {
    id: 'osprey',
    name: 'Osprey',
    giving: "it's giving feet rotate 180°, grips fish from any angle",
    desc: "Has a reversible outer toe that rotates backward to grip fish from any angle. Only hawk that dives feet-first into water. 70% dive success rate. The Osprey sprint approaches the problem from whatever angle the data presents and closes tickets at an unusually high success rate.",
    tags: ['focused','fast','precise','determined','feature','bugfix'],
  },
  {
    id: 'merlin',
    name: 'Merlin',
    giving: "it's giving small falcon, huge aggression, crows fear it",
    desc: "A small but intensely aggressive falcon that routinely chases birds twice its size and wins. Has moved into cities and learned to hunt in urban environments. The Merlin sprint has no respect for ticket size. Large blockers do not actually intimidate it.",
    tags: ['intense','fast','determined','bugfix','focused','bold'],
  },
  {
    id: 'anna_hummingbird',
    wikiTitle: "Anna's hummingbird",
    name: "Anna's Hummingbird",
    giving: "it's giving fastest heartbeat, fastest thought",
    desc: "Fastest heartbeat of any endotherm relative to body size — 1,260 beats per minute during flight. Makes a sharp metallic squeak. Males dive from 30m at 385 body-lengths per second — the fastest recorded movement relative to size in vertebrates. The Anna's sprint: smallest ticket, highest velocity.",
    tags: ['fast','intense','focused','feature','energetic','colorful'],
  },
  {
    id: 'eurasian_jay',
    name: 'Eurasian Jay',
    giving: "it's giving hides 5,000 acorns, finds every one",
    desc: "Buries up to 5,000 acorns each autumn in separate caches across its territory and retrieves them accurately through winter using spatial memory. Is directly responsible for forest regeneration across Europe. The Eurasian Jay sprint planted architecture for three future sprints while completing this one.",
    tags: ['smart','focused','patient','infra','determined','discovery'],
  },
  {
    id: 'superb_starling',
    name: 'Superb Starling',
    giving: "it's giving African plains iridescence, colony that feeds everyone",
    desc: "Metallic blue-green body, rusty-orange belly, white chest band. Lives in highly cooperative colonies where unrelated helpers assist in raising chicks. The Superb Starling sprint cross-functional by design — engineers helped on QA, QA helped on docs, docs helped on design. It shows.",
    tags: ['colorful','team','energetic','feature','bold','beautiful'],
  },
  {
    id: 'rainbow_lorikeet',
    name: 'Rainbow Lorikeet',
    giving: "it's giving every color at once, loudly, in your garden",
    desc: "Head is blue, chest is orange-red, belly is green, back is green with yellow. Has a brush-tipped tongue for nectar. Is an extremely loud daily presence wherever it lives. The Rainbow Lorikeet sprint brought every discipline together simultaneously and was not quiet about any of it.",
    tags: ['colorful','loud','chaotic','energetic','feature','bold'],
  },
  {
    id: 'sulphur_crested_cockatoo',
    name: 'Sulphur-crested Cockatoo',
    giving: "it's giving 80 years old, still screaming, still learning",
    desc: "Lives up to 80 years in captivity. Has been documented teaching itself to unlock latches — and teaching the technique to neighbors within weeks. Iconic white plumage, yellow crest raised when excited. The Cockatoo sprint carries institutional knowledge from 2016 and is still actively learning new tricks.",
    tags: ['chaotic','loud','smart','determined','weird','feature'],
  },
  {
    id: 'glossy_ibis',
    name: 'Glossy Ibis',
    giving: "it's giving iridescent in the right light, overlooked otherwise",
    desc: "Appears plain brown in flat light. In direct sun, shifts to deep copper, purple, and green iridescence. Expanding its range to new continents. The Glossy Ibis sprint was marked low priority in the ticket. Under direct stakeholder attention, it was clearly the sprint of the quarter.",
    tags: ['mysterious','hidden','beautiful','determined','colorful','feature'],
  },
  {
    id: 'pied_kingfisher',
    name: 'Pied Kingfisher',
    giving: "it's giving hovers in place, then strikes with certainty",
    desc: "Only kingfisher that hovers in mid-air independently without needing a perch. Can hunt over large open water. Black and white geometric patterning. The Pied Kingfisher sprint does not need a stable base to operate. It holds position in uncertainty and strikes when the window opens.",
    tags: ['focused','precise','fast','intense','bugfix','determined'],
  },
  {
    id: 'shoebill_night',
    wikiTitle: 'Shoebill',
    name: 'Shoebill — Night Mode',
    giving: "it's giving 2am commit, nobody saw, everything changed",
    desc: "The Shoebill is largely crepuscular — most active at dawn and dusk. Has been documented hunting lungfish in pitch darkness using the lateral line equivalent of sonar. The Night Mode sprint runs in the hours when Slack is off and the git log shows timestamps that raise questions.",
    tags: ['nocturnal','mysterious','focused','infra','intense','hidden'],
  },
  {
    id: 'hooded_merganser',
    name: 'Hooded Merganser',
    giving: "it's giving deployable crest, context-dependent presentation",
    desc: "Has a large fan-shaped white crest it can raise or lower instantly depending on social context. Uses different tactics for diving — serrated beak grips fish underwater. The Hooded Merganser sprint adjusts its communication style based on the audience but the technical execution is identical.",
    tags: ['focused','elegant','determined','feature','precise','colorful'],
  },
  {
    id: 'martial_eagle',
    name: 'Martial Eagle',
    giving: "it's giving highest-soaring, sees the whole board from up there",
    desc: "Africa's largest eagle. Soars at extreme altitude using thermals and can spot prey from 6km away. Vision so acute it can see a rabbit from the edge of the atmosphere, effectively. The Martial Eagle sprint starts with six weeks of silent observation. Then it lands on the solution.",
    tags: ['powerful','focused','patient','intense','discovery','determined'],
  },
  {
    id: 'spangled_cotinga',
    name: 'Spangled Cotinga',
    giving: "it's giving electric blue, just sitting there being correct",
    desc: "Males are vivid electric blue with a purple throat patch. Sit motionless at the tops of tall trees and simply exist at that color intensity. The Spangled Cotinga sprint has a very small ticket count, very high visual impact, and requires no justification from anyone.",
    tags: ['colorful','beautiful','mysterious','chill','feature','elegant'],
  },
  {
    id: 'turaco',
    wikiTitle: "Livingstone's turaco",
    name: "Livingstone's Turaco",
    giving: "it's giving one of the only true green pigments in birds",
    desc: "One of the only birds with a genuine green pigment (turacoverdin) rather than structural colour. Its crimson wing feathers contain copper-based turacin. The Turacos own something fundamentally different at the molecular level. The Turaco sprint has a genuine technological moat, not a trick.",
    tags: ['colorful','rare','focused','feature','beautiful','determined'],
  },
  {
    id: 'common_loon',
    name: 'Common Loon',
    giving: "it's giving haunting call across the lake, everything stops",
    desc: "Its wail carries for miles across lakes and has been used in film as the universal sound of wilderness. Can dive to 60 meters. Transforms from drab brown to a striking black-and-white checked pattern in breeding season. The Loon sprint's launch announcement makes the whole office pause.",
    tags: ['mysterious','powerful','determined','feature','elegant','nocturnal'],
  },
  {
    id: 'wandering_albatross',
    wikiTitle: 'Wandering albatross',
    name: 'Wandering Albatross — Solo',
    giving: "it's giving years in flight, lands for one reason only",
    desc: "Spends years at sea without touching land. Has the longest wingspan of any living bird at 3.5 meters. Returns to the same island to breed with the same partner, every other year, for life. The Solo sprint is the infrastructure marathon — no retro until it's done. It lands once. It matters.",
    tags: ['determined','patient','infra','persistent','chill','calm'],
  },
  {
    id: 'shoebill_v3',
    wikiTitle: 'Shoebill',
    name: 'Shoebill — The Verdict',
    giving: "it's giving six hours of stillness, one moment of judgment",
    desc: "Classified for decades as either a stork or a pelican relative. Modern genomics placed it in its own order. The debate about what kind of thing it is was resolved by looking more closely. The Verdict sprint paused the existing classification, ran the analysis, and shipped a new taxonomy.",
    tags: ['mysterious','focused','discovery','patient','dino','precise'],
  },
  {
    id: 'violet_backed_starling',
    name: 'Violet-backed Starling',
    giving: "it's giving angle-dependent iridescence, changes with perspective",
    desc: "Appears completely different depending on the angle of light — purple, violet, white, or silver. The same bird looks different to everyone in the room. The Violet-backed Starling sprint delivered something that each stakeholder described differently. All descriptions were correct.",
    tags: ['beautiful','mysterious','colorful','elegant','feature','discovery'],
  },
  {
    id: 'bengali_weaver',
    wikiTitle: 'Baya weaver',
    name: 'Baya Weaver',
    giving: "it's giving 500-loop woven nest, architectural flex",
    desc: "Males weave elaborate hanging nests from grass blades using over 500 separate woven loops. Each nest takes weeks. Females inspect them and reject substandard work. The Baya Weaver sprint has extraordinarily high code review standards. Multiple PRs have been closed and resubmitted from scratch.",
    tags: ['focused','precise','determined','infra','patient','feature'],
  },
  {
    id: 'malleefowl',
    name: 'Malleefowl',
    giving: "it's giving self-regulating compost incubator, built by one bird",
    desc: "Builds a mound of compost and soil up to a meter high that generates heat for incubating eggs. The male monitors temperature with its beak and adds or removes material to maintain 33°C exactly, for months. The Malleefowl sprint built its own CI/CD pipeline from scratch and monitors it manually.",
    tags: ['patient','determined','weird','infra','focused','precise'],
  },
  {
    id: 'greater_honeyguide',
    name: 'Greater Honeyguide',
    giving: "it's giving leads humans to beehives, takes its cut",
    desc: "Actively guides humans and honey badgers to beehives by flying ahead and calling. After the hive is broken open, it eats the wax and larvae. Cross-species collaboration with negotiated mutual benefit. The Honeyguide sprint partnered with an external team, shared the work, and took the wax.",
    tags: ['smart','curious','discovery','team','determined','weird'],
  },
  {
    id: 'painted_stork',
    name: 'Painted Stork',
    giving: "it's giving pink gradient wing tips, colonial nesting, organized chaos",
    desc: "Breeds in huge mixed-species colonies and uses tactile hunting — wades with beak open, snaps shut when it feels movement. Pink-tipped tertiary feathers. The Painted Stork sprint works in a multi-team environment, processes inputs in real time, and has the best visual output in the roadmap.",
    tags: ['colorful','team','chaotic','patient','feature','precise'],
  },
  {
    id: 'indian_roller',
    name: 'Indian Roller',
    giving: "it's giving aerial roll in breeding display, pure flex",
    desc: "Named for the rolling display flight males perform during courtship — full aerial rolls while calling loudly. Considered sacred in several South Asian traditions. Electric blue wings visible only in flight. The Indian Roller sprint had a memorable mid-sprint pivot that turned out to be exactly right.",
    tags: ['colorful','energetic','bold','chaotic','feature','beautiful'],
  },
  {
    id: 'jacobin_hummingbird',
    name: 'White-necked Jacobin',
    giving: "it's giving females dress as males to avoid harassment",
    desc: "Some females of this species adopt male plumage to avoid aggressive male behavior during feeding. They feed more efficiently and with less interruption. The Jacobin sprint realized the current process was inefficient, changed the interface, and velocity immediately improved.",
    tags: ['smart','focused','fast','discovery','weird','feature'],
  },
  {
    id: 'wheatear',
    name: 'Northern Wheatear',
    giving: "it's giving Alaska to Africa non-stop, 5g bird",
    desc: "A bird that weighs 25 grams migrates from Alaska to sub-Saharan Africa — one of the longest migrations relative to body size. Uses the same migration corridor as Ice Age ancestors. The Wheatear sprint scales with no additional resources. The existing architecture was always capable of this.",
    tags: ['determined','fast','persistent','infra','focused','intense'],
  },
  {
    id: 'curlew',
    wikiTitle: 'Eurasian curlew',
    name: 'Eurasian Curlew',
    giving: "it's giving call that defined the moor, now threatened",
    desc: "Its haunting, bubbling call defines the atmosphere of moorland across Europe and Asia. Populations in serious decline. Uses its long downcurved bill to probe deep into mud for invertebrates nobody else can reach. The Curlew sprint goes deeper than any other into the infrastructure sediment.",
    tags: ['mysterious','determined','focused','infra','patient','debt'],
  },
  {
    id: 'spix_macaw',
    name: "Spix's Macaw",
    giving: "it's giving thought extinct in wild, carefully rebuilt",
    desc: "Once the rarest bird in the world — declared extinct in the wild in 2000 with one wild male remaining. Reintroduced in Brazil in 2022 from captive-bred individuals. The Spix's Macaw sprint is the replatforming sprint: the original runs in captivity, a new wild instance was just deployed.",
    tags: ['rare','determined','hopeful','feature','colorful','infra'],
  },
  {
    id: 'superb_fairywren',
    name: 'Superb Fairywren',
    giving: "it's giving electric blue males, cooperative group defense",
    desc: "Males are brilliant electric blue during breeding season. Females help each other raise chicks across a cooperative family group. Has been documented teaching songs to unborn chicks inside the egg. The Fairywren sprint has team documentation so thorough that new members shipped on day one.",
    tags: ['colorful','team','fast','feature','energetic','beautiful'],
  },
  {
    id: 'satin_bowerbird',
    name: 'Satin Bowerbird',
    giving: "it's giving built an entire architecture just for the demo",
    desc: "Males build and decorate elaborate bowers — structures with no function other than impressing females. Steals blue objects obsessively because females prefer blue. Practices in private before performing. The Satin Bowerbird sprint spent three days on the demo environment. It was worth it.",
    tags: ['colorful','feature','determined','bold','smart','curious'],
  },
  {
    id: 'helmeted_hornbill',
    name: 'Helmeted Hornbill',
    giving: "it's giving solid ivory casque, rams rivals mid-air",
    desc: "The only bird with a solid casque on its beak — used for aerial casque-ramming contests with rivals. The casque is denser than ivory and carved by several cultures. The Helmeted Hornbill sprint resolves architectural debates with direct competitive evidence. Two approaches entered. One shipped.",
    tags: ['powerful','intense','chaotic','feature','determined','weird'],
  },
  {
    id: 'toco_toucan',
    name: 'Toco Toucan',
    giving: "it's giving largest beak proportionally, actually useful thermostat",
    desc: "The largest beak proportionally of any bird. Used as a thermoregulation device — blood flow through the beak increases or decreases to dump or retain heat. The enormous tool has a practical function nobody expected. The Toco Toucan sprint shipped a feature that turned out to be load-bearing infrastructure.",
    tags: ['colorful','weird','determined','infra','feature','bold'],
  },
  {
    id: 'secretary_bird_sprint',
    wikiTitle: 'Secretarybird',
    name: 'Secretary Bird — The Kick',
    giving: "it's giving 195 Newtons, five times body weight, one strike",
    desc: "Measured kick force: 195 Newtons — five times the bird's own body weight. Strikes in 15 milliseconds, faster than a blink. Walks 20-30km per day through the savanna locating targets. The Kick sprint spent the full sprint walking the codebase and resolved six blockers on the last day.",
    tags: ['determined','focused','intense','bugfix','powerful','fast'],
  },
  {
    id: 'blue_crane',
    wikiTitle: 'Blue crane',
    name: 'Blue Crane',
    giving: "it's giving South Africa's national bird, elegant threat display",
    desc: "South Africa's national bird. Steel-blue grey, long flowing feathers, striking threat display where wings are spread and neck extended. Performs elaborate duet dances with its mate. The Blue Crane sprint has a very clear owner, a formal threat response protocol, and ships paired features.",
    tags: ['elegant','determined','powerful','feature','team','beautiful'],
  },
  {
    id: 'white_throated_dipper',
    wikiTitle: 'White-throated dipper',
    name: 'White-throated Dipper',
    giving: "it's giving sings in winter, loudest when conditions are worst",
    desc: "Sings its full song during the harshest winter months while walking underwater in freezing rivers. One of the few birds that sings year-round. The White-throated Dipper sprint is the one nobody wanted — mid-December, difficult conditions — and it sang the whole way through.",
    tags: ['determined','persistent','infra','focused','calm','intense'],
  },
  {
    id: 'long_eared_owl',
    name: 'Long-eared Owl',
    giving: "it's giving ear tufts are not ears, still hears everything",
    desc: "The 'ear' tufts are purely for display — its actual ears are hidden asymmetrically on its skull for 3D sound location. Can pinpoint a mouse under 30cm of snow. The Long-eared Owl sprint operates in a noisy environment. The signal detection is exceptional despite the noise.",
    tags: ['nocturnal','focused','mysterious','infra','patient','precise'],
  },
  {
    id: 'barn_swallow',
    name: 'Barn Swallow',
    giving: "it's giving most widespread swallow, arrives before spring does",
    desc: "Most widely distributed swallow on Earth. Has expanded its range by following human structures for nesting. Arrives in the UK before the meteorological spring begins. The Barn Swallow sprint is always early. It uses existing infrastructure. It is, somehow, on every continent.",
    tags: ['fast','determined','team','feature','energetic','persistent'],
  },
  {
    id: 'eurasian_wren',
    wikiTitle: 'Eurasian wren',
    name: 'Eurasian Wren',
    giving: "it's giving Europe's loudest bird per gram of body weight",
    desc: "One of the loudest birds relative to body size in Europe. Weighs 10 grams and produces a song audible 500 meters away. Builds multiple 'cock nests' for the female to choose from. The Eurasian Wren sprint built three proof-of-concepts before scoping began. The team appreciated the options.",
    tags: ['loud','determined','focused','feature','energetic','persistent'],
  },
  {
    id: 'velvet_scoter',
    name: 'Velvet Scoter',
    giving: "it's giving all black, white wing patch, dives deep and returns",
    desc: "Almost entirely black diving duck with striking white wing patches visible only in flight. Dives up to 30 meters for mollusks. One of the quietest ducks. The Velvet Scoter sprint is the infra sprint that works completely in silence, surfaces with the exact dependencies requested, and disappears again.",
    tags: ['hidden','infra','focused','patient','determined','calm'],
  },
  {
    id: 'red_tailed_hawk',
    name: 'Red-tailed Hawk',
    giving: "it's giving ubiquitous but respected, sound of every film",
    desc: "The most common hawk in North America. Its scream is used in virtually every film that needs a 'dramatic bird sound' — often for eagles, which don't sound nearly as cinematic. The Red-tailed Hawk sprint is the sprint that runs every quarter. Reliable, respected, the sound of the system working.",
    tags: ['determined','focused','persistent','feature','powerful','calm'],
  },
  {
    id: 'palm_cockatoo',
    name: 'Palm Cockatoo',
    giving: "it's giving uses a stick as a drumstick, rhythmically",
    desc: "Holds a stick or seedpod in its foot and drums rhythmically on a hollow tree — one of the only non-human animals observed using a tool for rhythmic communication. Males drum to attract females. The Palm Cockatoo sprint schedules the retro and the launch demo at the peak of drum intensity.",
    tags: ['weird','smart','powerful','feature','chaotic','loud'],
  },
  {
    id: 'magnificent_frigatebird_alt',
    wikiTitle: 'Magnificent frigatebird',
    name: 'Magnificent Frigatebird — The Pouch',
    giving: "it's giving inflates to the size of a basketball, purely for attention",
    desc: "Males inflate a bright red gular pouch to basketball size during courtship. It takes 20 minutes to inflate. They sit in trees and wait for females to fly overhead. The Frigatebird Pouch sprint spent three sprints on the feature announcement. The feature itself took one afternoon.",
    tags: ['chaotic','loud','weird','feature','bold','energetic'],
  },
  {
    id: 'shoebill_coda',
    wikiTitle: 'Shoebill',
    name: 'Shoebill — Coda',
    giving: "it's giving bill-clapping as communication, no words needed",
    desc: "The Shoebill communicates by clapping its massive bill loudly — the sound carries across the swamp. Adults are completely silent otherwise. The Shoebill Coda sprint has one loud moment at launch. Everything leading up to it is documented only in commit messages.",
    tags: ['mysterious','focused','patient','infra','powerful','precise'],
  },
  {
    id: 'storks_relay',
    wikiTitle: 'White stork',
    name: 'White Stork',
    giving: "it's giving returns to the same chimney every year",
    desc: "Returns to the same nest on the same chimney or rooftop year after year — sometimes the same nest used for centuries by successive generations. Considered a symbol of good luck across Europe. The White Stork sprint is the annual one: same structure, same team, always produces the thing it always produces.",
    tags: ['determined','patient','team','feature','hopeful','calm'],
  },
  {
    id: 'shearwater',
    wikiTitle: 'Sooty shearwater',
    name: 'Sooty Shearwater',
    giving: "it's giving 65,000km migration, figure-eight around the whole ocean",
    desc: "Migrates in a figure-eight loop covering 65,000km annually — one of the longest documented migrations. Uses wind patterns across entire ocean basins for energy-free travel. The Shearwater sprint uses every existing service and platform correctly, adding zero infrastructure and covering enormous ground.",
    tags: ['determined','fast','infra','patient','persistent','focused'],
  },
  {
    id: 'shoebill_alpha',
    wikiTitle: 'Shoebill',
    name: 'Shoebill — Alpha',
    giving: "it's giving bows as greeting, demands bows back",
    desc: "Shoebills bow their heads as a greeting display and expect the gesture returned. Failure to reciprocate is noted. The Sprint is a senior stakeholder sprint. Acknowledgment of prior decisions is expected in the opening slides. The bill is watching.",
    tags: ['intense','patient','mysterious','powerful','focused','dino'],
  },
  {
    id: 'martial_eagle_survey',
    wikiTitle: 'Martial eagle',
    name: 'Martial Eagle — Survey',
    giving: "it's giving thermal-riding overview, sees all the tickets",
    desc: "Soars on thermals for hours scanning the landscape below before committing to a target. Has been documented soaring for six hours straight. The Survey sprint maps the entire system before the first line is written. The Martial Eagle does not rush the discovery phase.",
    tags: ['patient','focused','discovery','determined','powerful','calm'],
  },
  {
    id: 'whydah',
    wikiTitle: 'Pin-tailed whydah',
    name: 'Pin-tailed Whydah',
    giving: "it's giving tail 4x body length, seasonally deployed",
    desc: "Breeding males grow tail feathers four times their body length, shed them after the season, and grow them again the following year. Outside breeding season, indistinguishable from a sparrow. The Pin-tailed Whydah sprint ships one extraordinary feature per cycle and goes quiet otherwise.",
    tags: ['bold','colorful','weird','feature','determined','mysterious'],
  },
  {
    id: 'eurasian_golden_oriole',
    name: 'Eurasian Golden Oriole',
    giving: "it's giving heard constantly, almost never actually seen",
    desc: "One of Europe's most distinctive bird calls — a fluty, tropical yodel — heard clearly from dense woodland. Extremely difficult to spot despite being bright yellow. The Golden Oriole sprint's outputs are felt throughout the system. The team is hard to find in the org chart.",
    tags: ['colorful','mysterious','hidden','feature','elegant','determined'],
  },
  {
    id: 'resplendent_cotinga',
    wikiTitle: 'Banded cotinga',
    name: 'Banded Cotinga',
    giving: "it's giving sky blue with purple band, impossible in nature",
    desc: "The male is a vivid turquoise blue broken only by a purple breast band. Both colours are structural rather than pigment — interference patterns in the feather microstructure. The Cotinga sprint doesn't have a special color palette. The colors emerge from the underlying architecture.",
    tags: ['colorful','beautiful','mysterious','feature','elegant','rare'],
  },
  {
    id: 'hoatzin',
    name: 'Hoatzin',
    giving: "it's giving claws on wings as a chick, ancient design",
    desc: "Chicks have functional claws on their wings — a trait from dinosaur ancestors — and use them to climb out of the nest, swim, and climb back. Adults have an unusual fermentation-based digestive system. The Hoatzin sprint is running a very old architecture that predates modern frameworks. It works.",
    tags: ['weird','dino','determined','debt','infra','curious'],
  },
  {
    id: 'pelican_squadron',
    wikiTitle: 'Brown pelican',
    name: 'Brown Pelican — Formation',
    giving: "it's giving V formation cuts wind resistance for everyone behind",
    desc: "Brown Pelicans fly in formation just above wave height, using ground effect to reduce drag. Each bird benefits from the updraft of the one ahead. The Formation sprint optimized its own workflow and left documentation so thorough that every subsequent sprint runs 30% faster.",
    tags: ['team','determined','fast','infra','focused','patient'],
  },
  {
    id: 'firecrest',
    name: 'Firecrest',
    giving: "it's giving Europe's second smallest bird, striped crown on fire",
    desc: "One of Europe's smallest birds at 5-7 grams. Has a vivid orange-red crown stripe and a white eyebrow stripe. Constantly active. The Firecrest sprint has the smallest team, the most vivid output, and has not been still since kickoff. It will not slow down for the retro.",
    tags: ['fast','energetic','colorful','feature','intense','focused'],
  },
  {
    id: 'northern_mockingbird',
    name: 'Northern Mockingbird',
    giving: "it's giving 200 songs, all borrowed, fully owned",
    desc: "Can mimic over 200 distinct bird songs and incorporates new ones throughout its life. Has no original songs. Performs at night under streetlights. The Mockingbird sprint assembled solutions from across the industry, integrated them flawlessly, and presented the result at 2am as if it was always there.",
    tags: ['chaotic','smart','loud','feature','nocturnal','curious'],
  },
  {
    id: 'snowy_plover',
    name: 'Snowy Plover',
    giving: "it's giving broken-wing display, decoy as a feature",
    desc: "Leads predators away from its nest by performing a convincing broken-wing display — dragging a wing, calling distressed — until the threat is far enough away. Then flies off perfectly. The Snowy Plover sprint deployed a decoy while the real work happened in a parallel branch.",
    tags: ['smart','hidden','mysterious','bugfix','determined','infra'],
  },
  {
    id: 'wrybill',
    name: 'Wrybill',
    giving: "it's giving only bird with a bill that bends sideways",
    desc: "The only bird in the world with a bill that curves to the right — used to flip stones sideways while searching for invertebrates. Evolved for one specific feeding niche. The Wrybill sprint built a utility that only works in one specific context. That context is critical path.",
    tags: ['weird','precise','focused','infra','discovery','determined'],
  },
  {
    id: 'shoebill_origin',
    wikiTitle: 'Shoebill',
    name: 'Shoebill — Origin',
    giving: "it's giving 30 million year old fossil record, still relevant",
    desc: "Shoebill fossil records extend back 30 million years. The basic body plan has not required major revision in three decades of geological time. The Origin sprint is the system design sprint. The architecture is not being changed. The architecture has already survived longer than the organisation.",
    tags: ['dino','patient','determined','infra','powerful','focused'],
  },
  {
    id: 'spoon_winged_lapwing',
    wikiTitle: 'Spur-winged lapwing',
    name: 'Spur-winged Lapwing',
    giving: "it's giving bony wing spur, will absolutely use it",
    desc: "Has a sharp bony spur at the bend of each wing. Uses them to fight rivals and defend nests with genuine aggression. Makes a loud metallic alarm call. The Spur-winged Lapwing sprint has a very clear definition of done and will flag any PR that doesn't meet it. Loudly.",
    tags: ['determined','loud','focused','intense','bugfix','bold'],
  },
  {
    id: 'shoebill_v2',
    wikiTitle: 'Shoebill',
    name: 'Shoebill — V2',
    giving: "it's giving prehistoric, already updated once in 30M years",
    desc: "Shoebills represent a successful second evolutionary iteration — early ancestors were smaller and more heron-like. The Version Two added the clog-shaped bill, the blue-grey armor plating, and the five-foot frame. The V2 sprint is the redesign that nobody asked for and everyone needed.",
    tags: ['focused','powerful','feature','dino','intense','determined'],
  },
  {
    id: 'paradise_tanager',
    name: 'Paradise Tanager',
    giving: "it's giving nine colors, somehow cohesive",
    desc: "Has nine distinct color regions: scarlet, sky blue, black, turquoise, yellow-green, blue, purple, green, and red. They cohere completely into something that looks designed. The Paradise Tanager sprint was touched by seven teams. The integration is seamless. Nobody can explain it.",
    tags: ['colorful','beautiful','weird','feature','team','bold'],
  },
  {
    id: 'kagu',
    name: 'Kagū',
    giving: "it's giving crest like a crown, nearly flightless, deeply endangered",
    desc: "New Caledonia's national bird. Has an elaborate spiky crest, loud nasal call, and unusual spotted wing pattern used in threat displays. Nearly flightless despite having large wings. The Kagū sprint spent the first week building elaborate scaffolding and then shipped entirely by running.",
    tags: ['weird','determined','rare','discovery','chaotic','bold'],
  },
];
